#!/bin/sh

# OPTIND reset
OPTIND=1

# getopts vars:
arg=""
switch=0

while getopts "h?vf:" opt; do
    case "$opt" in
    h|\?)
        usage
        exit 0
        ;;
    v)  switch=1
        ;;
    f)  arg=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

echo "switch=${switch}, arg='${arg}', rest: $*"