#!/bin/sh
# inspired by https://gist.github.com/brpaz/e4db5057f4d24c9b2500

# OPTIND reset
OPTIND=1

# getopts vars:
arg=""
switch=0

while getopts "h?sa:" opt; do
    case "$opt" in
    h|\?)
        usage
        exit 0
        ;;
    s)  switch=1
        ;;
    a)  arg=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

echo "switch=${switch}, arg='${arg}', rest: $*"